name: build and test

on:
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-22.04
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install essentials and compiler
              run: |
                sudo apt-get update
                sudo apt-get install -y g++

            - name: Install cmake
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '4.2.3'

            - name: Build
              run: |
                cmake -B build
                cmake --build build

            - name: Run tests
              run: | 
                echo "🔍 Running Test 1..."
                output=$(./build/programm "hello")

                if [ $? -ne 0 ]; then
                    echo "❌ Test 1 FAILED: expected exit code 0"
                    exit 1
                fi
                if [ "$output" != "hello" ]; then
                    echo "❌ Test 1 FAILED: wrong output"
                    exit 1
                fi
                echo "✅ Test 1 PASSED"

                echo "🔍 Running Test 2..."
                ./build/programm > /dev/null 2>&1
                rc=$?
                echo "Test 2: exit_code=$rc"
                
                if [ $rc -ne 1 ]; then
                echo "❌ Test 2 FAILED: expected exit code 1, got $rc"
                exit 1
                fi
                echo "✅ Test 2 PASSED"
                
                echo "🎉 All tests passed!"
