name: build and test

on:
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-22.04
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install essentials and compiler
              run: |
                sudo apt-get update
                sudo apt-get install -y g++

            - name: Install cmake
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '4.2.3'

            - name: Build
              run: |
                cmake -B build
                cmake --build build

            - name: Tests
              run: | 
                ./build/programm hello

                exit_code=$?

                if [ $exit_code -eq 0 ]; then
                    echo "Test 1 result - OK"
                else
                    echo "Test 1 result - FAILURE"
                fi

                ./build/programm || true

                exit_code=$?

                if [ $exit_code -eq 1 ]; then
                    echo "Test 2 result - OK"
                else
                    echo "Test 2 result - FAILURE"
                fi
